#!/usr/bin/env perl

# sprofpp - a simple script akin to the standard dprofpp.
# It sorts and displays Devel::SmallProf output on 'total time used' field,
# or any other numeric field.
#
# Usage:
# First, generate smallprof.out:
# perl -I. -d:SmallProf scripts/viper.pl
#
# Then, print statistics based on it:
# (By default, FILE is smallprof.out, and FIELD is 2 (wallclock time)):
# perl scripts/sprofpp [FILE] [SORT_FIELD_NUMBER]
#
# Alternatively, you can use DProf and its existing dprofpp:
# perl -I. -d:DProf scripts/viper.pl
# dprofpp
#
# Davor Ocelic <docelic@crystallabs.io>
# Crystal Labs, https://crystallabs.io/
# Released under GPL v3.

use warnings;
use strict;
use Fatal qw/open/;

open my $prof, $ARGV[0]|| 'smallprof.out';
my $field= $ARGV[1]|| 2;

my @sorted = sort {
	my @a= split /\s+/, $b;
	my @b= split /\s+/, $a;

	$a[$field] <=> $b[$field]

} <$prof>;

close $prof;

print join '', @sorted;
